Update verify_push.yml

diff --git a/.github/workflows/verify_push.yml b/.github/workflows/verify_push.yml
--- a/.github/workflows/verify_push.yml
+++ b/.github/workflows/verify_push.yml
@@ -16,11 +16,21 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
-          python-version: '3.12.3'  # Specify your Python version here
+          python-version: '3.x'  # Specify your Python version here
 
       - name: Install dependencies
-        run: python -m pip install pytest
-          
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt  # If you have any dependencies
+
+      - name: Check if test_script.py exists
+        run: |
+          if [ -f "test_script.py" ]; then
+            echo "test_script.py found."
+          else
+            echo "test_script.py not found. Exiting."
+            exit 1
+          fi
+
       - name: Run Python command
-        run: python /c/Users/evgenyb/evgenybl/test_script.py  # Replace with your Python command/script path
- 
+        run: python test_script.py  # Replace with your Python command/script path
